### ISSUE TITLE
Document $environment

### ISSUE THREAD

**Issue by hassy** [shoreditch-ops/artillery-docs#22]
https://github.com/shoreditch-ops/artillery/issues/195

**Comment by BenSayers** [comment]
Where is this actually documented? The only reference I could find is on this page that doesn't actually explain the feature:
https://artillery.io/docs/http-reference/#logging

**Comment by hassy** [comment]
Thanks @BenSayers, documented now (in https://github.com/shoreditch-ops/artillery-docs/commit/16bf0b474d9c85d98e9cf0d8e85375688d29a17a). The website should be updated soon.

**Comment by BenSayers** [comment]
Thanks mate!
